/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogIn.java
 *
 
 */

/**
 *
 * @author megha
 */
import java.sql.*;
public class LogIn extends javax.swing.JFrame {

    /** Creates new form LogIn */
    public LogIn() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        loginBTN = new javax.swing.JButton();
        regLBL = new javax.swing.JLabel();
        InvalidLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Curlz MT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("QUIZ TIME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleParent(this);

        jLabel3.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("LOG IN TO CONTINUE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Curlz MT", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, -1));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, -1));

        Password.setEchoChar('*');
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 160, -1));

        jLabel5.setFont(new java.awt.Font("Curlz MT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LogIn ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 90, -1));

        loginBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        loginBTN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginBTN.setText("Log In");
        loginBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(loginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, 40));

        regLBL.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        regLBL.setForeground(new java.awt.Color(51, 255, 102));
        regLBL.setText("Not Yet a Member.. Click here to register");
        regLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regLBLMouseClicked(evt);
            }
        });
        getContentPane().add(regLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 440, -1));

        InvalidLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InvalidLBL.setForeground(new java.awt.Color(153, 0, 153));
        getContentPane().add(InvalidLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 200, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        String PWord = new String(Password.getPassword());
        String Id = ID.getText();
        try   {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/quizdb", "root", "kvuc");
            Statement stmt = conn.createStatement();
            stmt = conn.createStatement();
            String sql = "select * from LogIn where ID = '" + Id + "'";
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
            String str = rs.getString("Password");
            if(str.equals(PWord))
            {
                 Menu m = new Menu(Id);
                  m.setVisible(true);
                 this.setVisible(false);
            }
            else
            {
                 InvalidLBL.setText("Incorrect ID or Password");
            }
        } catch (Exception e) { InvalidLBL.setText("Incorrect ID or Password");}
}//GEN-LAST:event_loginBTNActionPerformed

    private void regLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regLBLMouseClicked
        Register r = new Register();
        r.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_regLBLMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JLabel InvalidLBL;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel regLBL;
    // End of variables declaration//GEN-END:variables

}
